### ISSUE TITLE
unify imageVectorOverwrite location in helm values

### ISSUE THREAD

**Issue by Diaphteiros** [gardener/gardener-extension-runtime-gvisor#61]
As far as I have seen, the runtime-gvisor extension is the only extension where the image vector can be overwritten at `.image.imageVectorOverwrite` in the chart's values file. For all other extensions, the `imageVectorOverwrite` node is at top-level in the values file.

To make this even more confusing, this is how it is described in the values file:
```yaml
image:
  repository: eu.gcr.io/gardener-project/gardener/extensions/runtime-gvisor
  tag: latest
  pullPolicy: IfNotPresent
# imageVectorOverwrite: |
...
```
The line with the (commented out) 'imageVectorOverwrite' is not indented and thus at the same position as it is in the example values files of the other extensions. But there, when commented in, the 'imageVectorOverwrite' must not be indented, whereas for this extension, it has to be.

It would be nice to have this unified among all extensions.
